import { Header } from "@/widgets/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../../shared/styles/global.scss'
import ReduxToolkitProvider from "@/shared/providers/reduxToolkit";
import { ThemeProvider } from "next-themes";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Navbar } from "@/widgets/navbar";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={inter.className} >
        <ReduxToolkitProvider>
          <AntdRegistry>
            <ConfigProvider >
          <ThemeProvider>
            <NextIntlClientProvider messages={messages} >
              <Header />
              <main><div className="container template" ><div className="main__navbar"><Navbar/></div><div className="main__content" >{children}</div></div></main>
            </NextIntlClientProvider>
          </ThemeProvider>
          </ConfigProvider>
          </AntdRegistry>
        </ReduxToolkitProvider>
      </body>
    </html>
  );
}
