import { Header } from "@/widgets/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../../shared/styles/global.scss'
import ReduxToolkitProvider from "@/shared/providers/reduxToolkit";
import { ThemeProvider } from "next-themes";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={inter.className} >
        <ReduxToolkitProvider>
          <ThemeProvider >
            <NextIntlClientProvider messages={messages} >
              <Header />
              {children}
            </NextIntlClientProvider>
          </ThemeProvider>
        </ReduxToolkitProvider>
      </body>
    </html>
  );
}
