version: '3.9'

services:
  db:
    build:
      context: ../db
      dockerfile: Dockerfile
    restart: always
    ports:
      - '127.0.0.1:5432:5432'

  back:
    build:
      context: ../back
      dockerfile: Dockerfile
    restart: always
    ports:
      - '127.0.0.1:5000:5000'
    depends_on:
      - db

  front:
    build:
      context: ../front
      dockerfile: Dockerfile
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - back