import { Header } from "@/widgets/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../shared/styles/global.scss'
import ReduxToolkitProvider from "@/shared/providers/reduxToolkit";
import { LoadTheme } from "@/entities/theme";
import ThemeProvider from "@/shared/providers/themeProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <ReduxToolkitProvider>
      <ThemeProvider font={inter} >
          <LoadTheme/>
        <Header/>
        {children}
        </ThemeProvider>
        </ReduxToolkitProvider>
    </html>
  );
}
